# version
server:
  servlet:
    context-path: /api/v1
#    context-path-internal-api: /api/v1/internal

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:flash_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# actuator config
# the management.info.env.enabled needed to be set to true to show info
# see: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#actuator-env-infocontributor-disabled-by-default
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      path-mapping:
        health: healthcheck
      exposure:
        include: "*"

# info. will be presented when hitting the actuator/info endpoint
info:
  app:
    name: Sensitive words application
    version: 1.0.0
    description: A simple application with services to maintain sensitive words and to redact words of a message

debug: true


